import {
    DEV_BACKEND_URL,
    DEV_FB_API_KEY,
    DEV_FB_AUTH_DOMAIN,
    DEV_FB_DATABASE_URL,
    DEV_FB_PROJECT_ID,
    DEV_FB_STORAGE_BUCKET,
    DEV_FB_MESSAGING_SENDER,
    DEV_SECRET_KEY,
    DEV_ANDROID_CLIENT_ID,
    DEV_EXPO_CLIENT_ID,

    PROD_BACKEND_URL,
    PROD_FB_API_KEY,
    PROD_FB_AUTH_DOMAIN,
    PROD_FB_DATABASE_URL,
    PROD_FB_PROJECT_ID,
    PROD_FB_STORAGE_BUCKET,
    PROD_FB_MESSAGING_SENDER,
    PROD_SECRET_KEY,
    PROD_ANDROID_CLIENT_ID,
    PROD_EXPO_CLIENT_ID,
} from '@env'

const devEnvironmentVariables = {
    BACKEND_URL:DEV_BACKEND_URL,
    FB_API_KEY:DEV_FB_API_KEY,
    FB_AUTH_DOMAIN:DEV_FB_AUTH_DOMAIN,
    FB_DATABASE_URL:DEV_FB_DATABASE_URL,
    FB_PROJECT_ID:DEV_FB_PROJECT_ID,
    FB_STORAGE_BUCKET:DEV_FB_STORAGE_BUCKET,
    FB_MESSAGING_SENDER:DEV_FB_MESSAGING_SENDER,
    SECRET_KEY:DEV_SECRET_KEY,
    ANDROID_CLIENT_ID:DEV_ANDROID_CLIENT_ID,
    EXPO_CLIENT_ID:DEV_EXPO_CLIENT_ID,
};

const prodEnvironmentVariables = {
    BACKEND_URL:PROD_BACKEND_URL,
    FB_API_KEY:PROD_FB_API_KEY,
    FB_AUTH_DOMAIN:PROD_FB_AUTH_DOMAIN,
    FB_DATABASE_URL:PROD_FB_DATABASE_URL,
    FB_PROJECT_ID:PROD_FB_PROJECT_ID,
    FB_STORAGE_BUCKET:PROD_FB_STORAGE_BUCKET,
    FB_MESSAGING_SENDER:PROD_FB_MESSAGING_SENDER,
    SECRET_KEY:PROD_SECRET_KEY,
    ANDROID_CLIENT_ID:PROD_ANDROID_CLIENT_ID,
    EXPO_CLIENT_ID:PROD_EXPO_CLIENT_ID,
};

export default __DEV__?devEnvironmentVariables:prodEnvironmentVariables;